language: objective-c
xcode_workspace: BitmarkLib.xcworkspace # path to your xcodeproj folder
xcode_scheme: BitmarkLib
osx_image: xcode8.2

before_install:
  - gem install xcpretty

script:
  - xcodebuild -scheme BitmarkLib -workspace BitmarkLib.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
