language: objective-c
osx_image: xcode9
branches:
  only:
    - master

before_install:
  - gem install xcpretty

install:
  - travis_wait pod install --repo-update

script:
  - xcodebuild -scheme BitmarkSDK -workspace BitmarkSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3.1' -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
