language: swift
xcode_workspace: BitmarkLib.xcworkspace # path to your xcodeproj folder
xcode_scheme: BitmarkLib
osx_image: xcode9.0

before_install:
  - gem install xcpretty
  - pod repo update

script:
  - xcodebuild -scheme BitmarkLib -workspace BitmarkLib.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.3' build test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
