language: swift
osx_image: xcode10.2
branches:
  only:
    - master

env:
  matrix:
    - DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=12.0'
    - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=11.0'

before_install:
  - gem install xcpretty
  - brew install carthage

install:
  - carthage update
  - cd Sample/swift-sdk-sample && pod update

script:
  - xcodebuild -scheme BitmarkSDK -workspace BitmarkSDK.xcworkspace -sdk iphonesimulator -destination $DESTINATION -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test | xcpretty
  - xcodebuild -scheme swift-sdk-sample -workspace swift-sdk-sample.xcworkspace -sdk iphonesimulator -destination $DESTINATION build

after_success:
- bash <(curl -s https://codecov.io/bash)
