language: swift
osx_image: xcode10.2
branches:
  only:
    - master

env:
  matrix:
    - NAME="iPhone 8" OS="12.0"
    - NAME="iPhone 6" OS="11.0"

before_install:
  - gem install xcpretty
  - brew install carthage

install:
  - carthage update

script:
  - xcodebuild -scheme BitmarkSDK -workspace BitmarkSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=$NAME,OS=$OS' -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test | xcpretty
  - cd Sample/swift-sdk-sample && pod update
  - xcodebuild -scheme swift-sdk-sample -workspace swift-sdk-sample.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=$NAME,OS=$OS' build

after_success:
- bash <(curl -s https://codecov.io/bash)
