language: swift
osx_image: xcode10.2
branches:
  only:
    - master
    - v1

before_install:
  - gem install xcpretty
  - brew install carthage

install:
  - carthage update

script:
  - xcodebuild -scheme BitmarkSDK -workspace BitmarkSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0.1' -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test | xcpretty
  - xcodebuild -scheme BitmarkSDK -workspace BitmarkSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
