language: objective-c
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
branches:
  only:
    - master
    - develop

before_install:
  - gem install xcpretty

install:
  - pod install

script:
  - xcodebuild -scheme BitmarkSDK -workspace BitmarkSDK.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0.1' -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
